version: '3.6'

services:

  mysql_db:
    image: mysql:5.7
#    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init_db.sql
    volumes:
      - ./init_db.sql:/data/application/init_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  akhq:
    image: tchiotludo/akhq:0.17.0
    platform: linux/amd64
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9093"
    ports:
      - 8081:8080
    links:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
#    platform: linux/amd64
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.5.3
#    platform: linux/amd64
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_COMPRESSION_TYPE: gzip
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: 9091
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - 9092:9092
    links:
      - zookeeper
